### ISSUE TITLE
Edited the wiki

### ISSUE THREAD

**Issue by kar200** [rememberYou/dotfiles#2]
HI, thanks for the guide the colors are perfect (as well as all the small commands0.

I edited your wiki thinking it will first wait for your approval before going through but apparently it got published straight away. Please have a look.

**Comment by rememberYou** [comment]
Hey @kar200, thanks for your interest in these dotfiles, I'm glad that it has served you as much as it serves me when I have to reinstall Arch Linux :-)

Indeed, it would be necessary to first mount `mnt` before creating the folders:
```sh
SSD_MOUNTS="autodefrag,compress=lzo,discard,inode_cache,noatime,nodev,rw,space_cache,ssd"
mount -o subvol=root,$SSD_MOUNTS /dev/mapper/lvmvg-root /mnt
mkdir -p /mnt/{boot,home}
```

Thank you for this change! You have done well. Feel free to make others as needed and/or to make recommendations.

**Comment by kar200** [comment]
No worries although I did not manage to boot with the new system so I just reverted to ext4 as I need a partition for my windows.

By the way you do not export any of the Wayland variables and quteebrowser didn't start.

Also I will need to export the variables.

Do you have any hidpi screen by any chance with fractional scaling ?

**Comment by rememberYou** [comment]
I didn't add the export variables for Wayland in the Wiki about installing Sway. It is true that it should be done.

I use a dual screen with a 2K screen for my ThinkPad and I put my 4K screen in Ultra HD:
```sh
[22:22:32] someone:~ $ swaymsg -t get_outputs
Output eDP-1 'Unknown 0x0502 0x00000000'
  Current mode: 2560x1440 @ 60.004002 Hz
  Position: 1920,0
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    2560x1440 @ 60.004002 Hz

Output DP-1 'Iiyama North America PLG2888UH 0x00000101' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 66.667000 Hz
    640x480 @ 72.808998 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 56.250000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 72.188004 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 70.069000 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.810001 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 59.953999 Hz
    1600x1200 @ 60.000000 Hz
    1920x1080 @ 23.976000 Hz
    1920x1080 @ 24.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz
    1920x1200 @ 59.884998 Hz
    2048x1152 @ 60.000000 Hz
    2560x1440 @ 59.951000 Hz
    1920x2160 @ 60.000000 Hz
    3840x2160 @ 29.969999 Hz
    3840x2160 @ 30.000000 Hz
```

The main reason my 4K screen is in ultra-HD is to avoid using fractional scaling which should be avoided according to the sway developers.

For environment variables, here is what I use so that Java and Qt 5 applications are not blurry:
```sh
# Fix issues with Java applications and Wayland.
export _JAVA_AWT_WM_NONREPARENTING=1

# Allows Qt 5 to enable Wayland support.
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
```

The rest of the environment variables that I use are available here : https://github.com/rememberYou/dotfiles/blob/736f4ee22da45d3411dec8ddfc6afc07af0ec196/sh/.config/sh/environ

I hope this can help you, don't hesitate if you want more information :-)
